admin_index:
    path: /
    defaults: { _controller: "AdminBundle:Default:index" }
    requirements:
        _method: GET

admin_show_users:
    path: /users
    defaults: { _controller: "AdminBundle:User:index" }
    requirements:
        _method: GET