admin_index:
    path: /
    defaults: { _controller: "AdminBundle:Default:index" }
    requirements:
        _method: GET

admin_show_users:
    path: /users
    defaults: { _controller: "AdminBundle:User:index" }
    requirements:
        _method: GET

admin_update_user:
    path: /users/edit/{id}
    defaults: { _controller: "AdminBundle:User:update" }
    requirements:
        _method: PATH

admin_create_user:
    path: /users/create
    defaults: { _controller: "AdminBundle:User:create" }
    requirements:
        _method: POST

admin_delete_user:
    path: /users/delete/{id}
    defaults: { _controller: "AdminBundle:User:delete" }
    requirements:
        _method: GET

admin_change_password:
    path: /users/change_password/{id}
    defaults: { _controller: "AdminBundle:User:changePassword" }
    requirements:
        _method: GET