admin_index:
    path: /
    defaults: { _controller: "AdminBundle:Default:index" }
    requirements:
        _method: GET

admin_show_users:
    path: /users
    defaults: { _controller: "AdminBundle:User:index" }
    requirements:
        _method: GET

admin_update_user:
    path: /users/edit/{id}
    defaults: { _controller: "AdminBundle:User:update" }
    requirements:
        _method: GET

admin_create_user:
    path: /users/create
    defaults: { _controller: "AdminBundle:User:create" }
    requirements:
        _method: GET
